### ISSUE TITLE
Using the horizonpedia hashtag leads to a screen showing Error 301

### ISSUE THREAD

**Issue by KevinCCucumber** [EhsanKia/CatalogScanner#21]
If I call this [link](https://catalogscanner.horizonpedia.com/oVVrLQym9Pn) I get an error 301
This is only the case when viewing horizonpedia pages.
Exampletweet: https://twitter.com/CatalogScanner/status/1566466343729332228

Could you fix it so the raw json gets returned when someone tries to call the link?

**Comment by EhsanKia** [comment]
I'm not sure how this is an issue with CatalogScanner. That seems to be a bug on horizonpedia's side. Are you correctly calling nook.lol or are you still using the old ehsan.lol domain?

**Comment by KevinCCucumber** [comment]
Twitter does funny things. I am using the correct url, but copying the link copies a link with twitters link shortener and its completely unreadable for the app.
