### ISSUE TITLE
suggestion to make a reverse import list

### ISSUE THREAD

**Issue by h3oCharles** [EhsanKia/CatalogScanner#4]
hey there,

i see that there's a missing recipes button to show a list of missing recipes, but copying it just gives a list of missing things.
what if you could make an invert of a list? like, a list of what you _**don't**_ have?

**Comment by EhsanKia** [comment]
I'm not quite sure I understand, can you explain more? Are you saying you want the reverse list to be importable into other apps like a normal list?

**Comment by h3oCharles** [comment]
the list that i recently made ( https://nook.lol/M5EkP0pPaa1 ) contains some items. my suggestion involves a way of making a link of a list of missing items

so instead of a list of 68 items (in case of this link), i'd click a button to get a list of 567 items, all importable to external sites

this would make to-do and "Looking For" lists much easier to make

**Comment by EhsanKia** [comment]
I see, I can make it so that https://nook.lol/M5EkP0pPaa1_missing is a special list that is the inverse, and hopefully to external websites it'll be fully transparent and look like any other list code, but on my backend it'll do the magic. I'll let you know when it's ready.

**Comment by EhsanKia** [comment]
Alright, should work now, although with no underscore, just adding "missing" suffix. Let me know if it works for you. Should hopefully work seamlessly with all supported websites. Also shows the link on the missing page:  https://nook.lol/M5EkP0pPaa1/missing

**Comment by h3oCharles** [comment]
yup, perfect, thank you so much
